# Setup
title:        Silly Potty
tagline:      Esperimenti di Data Visualization con gli Open Data del Parlamento Italiano.
baseurl:      "/silly-potty"
paginate:     1

# About/contact
author:
  name:       Paolo Montesel
  url:        https://github.com/kenoph

# Gems
gems:
  - jekyll-paginate

#Others
#markdown: redcarpet
markdown: kramdown
